blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Wiki
    url: https://github.com/srealmoreno/rae-tesis/wiki
    about: Wiki
  - name: ğŸ’¬ Community Discussions
    url: https://github.com/srealmoreno/rae-tesis/discussions
    about: Please ask and answer questions here.
  - name: ğŸ“œ Contribute guidelines
    url: https://github.com/srealmoreno/rae-tesis/blob/main/docs/CONTRIBUTING.md
    about: Guidelines for contributing to the project.
  - name: ğŸ“â€‹ Code of Conduct
    url: https://github.com/srealmoreno/rae-tesis/blob/main/docs/CODE_OF_CONDUCT.md
    about: Code of conduct for the project.
