name: ‚ôªÔ∏è Sync Labels

on:
  workflow_dispatch:

  push:
    paths: [.github/labels/labels.yml]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  labels:
    name: ‚ôªÔ∏è Sync labels
    runs-on: ubuntu-20.04
    steps:
      - name: ‚§µÔ∏è Check out code from GitHub
        uses: actions/checkout@v3

      - name: üöÄ Run Label Sync
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels/labels.yml

